CREATE SCHEMA IF NOT EXISTS `starsator` DEFAULT CHARACTER SET utf8 ;
USE `starsator` ;

CREATE TABLE IF NOT EXISTS `starsator`.`star` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `distance` FLOAT NOT NULL,
  PRIMARY KEY (`id`))